/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import edu.curso.DAO.CriaBanco.CriaBanco;
import edu.curso.Fronteira.LoginView;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    public void start(Stage stage) {
        try {
            CriaBanco.criarBanco();
            CriaBanco.criarTabelas();
        } catch (Exception e) {
            e.printStackTrace();
        }

        Contexto.iniciar(stage);
        Contexto.setTela(new LoginView());
    }
}
